[package]
name = "skyme-rime-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
skyme-common = { path = "../common" }
bitflags = "2"
log = "0.4"
libloading = "0.8"

[build-dependencies]
pkg-config = "0.3"
bindgen = { version = "0.70", optional = true }

[features]
default = []
bindgen = ["dep:bindgen"]
